### ISSUE TITLE
Probably should use from setuptools instead of from distutils.core.

### ISSUE THREAD

**Issue by detrout** [flying-sheep/legacy-api-wrap#2]
Hi, while building a package of legacy-api-wrap I saw some warnings during the build.

```
I: pybuild base:232: python3.9 setup.py clean 
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'extras_require'
  warnings.warn(msg)
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running clean
```

Searching for the error message led me to this bug https://github.com/google/gdata-python-client/issues/66 recommending the change to ```from setuptools import setup``` 

Which I tried, and it gets rid of the warning.

**Comment by flying-sheep** [comment]
Hm, the package isn’t actually using setuptools. The standard way of building using `python -m build` works without warnings!
