### ISSUE TITLE
Licensing Questions

### ISSUE THREAD

**Issue by dani-ham** [flying-sheep/legacy-api-wrap#45]
Hi
legacy-api-wrap is GPL3, but can I use it under a compatible license (e.g. BSD3)?
Also, are there any plans to change the license of legacy-api-wrap to be like scanpy?

thanks

**Comment by flying-sheep** [comment]
Hi, sure, if you have a good reason I can change the license or simply give you the right to use it under the terms of another license.

Two questions:
1. What does “compatible” mean? Compatible to what?
2. Why do you want this? Do you e.g. want to make modifications to its code without contributing them back? I wonder why, it’s such a small thing, you could just contribute them back. Or is this e.g. some company policy compliance thing?

**Comment by dani-ham** [comment]
Thank you for your reply.

As for your question, as you asked, it is due to company policy.
My company wants to avoid the GPL license, so I wanted to check if other licenses would be okay.

The reason for "compatible" is the same, but I was mistaken.
because I also asked about the license for squidpy in the past.
link: https://github.com/scverse/squidpy/issues/626
They said it was "compatible," but it was probably due to the Qt license.

Thank you for your answer.

**Comment by flying-sheep** [comment]
As said, it’s a tiny package, so if you tell me what company we’re talking about, I can give them a one-time exception (that’s less work than re-licensing the package, and I can reconsider that if more requests come in).

Independently, please ask your company to reconsider their open-source policies. There’s no practical reason for your company to do this: it’s extremely unlikely you need to modify legacy-api-wrap, and all but impossible that you would do so in a way that contains some kind of company IP. So the only thing we’re talking about here is bureaucracy.

**Comment by dani-ham** [comment]
Thank you so much.

I will try to persuade the company.

I understand the company's feelings,
but personally I feel the same way you.

please closing this thread

**Comment by flying-sheep** [comment]
That’s great!

As said, I’m happy to also give your company an exception if you tell me what name to write into it.
